num1=int(input())
num2=int(input())
print("Sum:"+str(num1+num2))
print("Difference:"+str(num1-num2))
print("Product:"+str(num1*num2))
print("Quotient:"+str(num1//num2))
print("Remainder:"+str(num1%num2))
